// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShadowViewer.Sdk.Database;

#nullable disable

namespace ShadowViewer.Sdk.Database.Migrations
{
    [DbContext(typeof(ShadowDbContext))]
    [Migration("20261009072705_InitialSdk")]
    partial class InitialSdk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("ShadowViewer.Sdk.Cache.CacheZip", b =>
                {
                    b.Property<string>("Md5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CachePath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ComicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Md5", "Sha1");

                    b.ToTable("CacheZip", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Sdk.Models.ShadowTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForegroundHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("unique_shadow_tag_name");

                    b.ToTable("ShadowTag", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
