name: Publish Nuget Packages

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (例如 1.0.0)'
        required: true
        type: string
  push:
    tags:
      - '*.*.*'   # 匹配 1.0.0 这种格式的 tag

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: ShadowViewer.Sdk
      RELEASE_TAG: ${{ github.event.inputs.release_tag || github.ref_name }}
    steps:
      - uses: mickem/clean-after-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          cache: false
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Use Release Tag
        run: echo "The release tag is $env:RELEASE_TAG"

      - name: Create NugetPackages
        run: |
          mkdir NugetPackages

      - name: Build Packages
        run: |
          dotnet restore $env:Solution_Name/$env:Solution_Name.csproj --locked-mode
          dotnet build $env:Solution_Name/$env:Solution_Name.csproj -p:Configuration=Release

      - name: Push package to Nuget registry
        run: |
          cd NugetPackages
          ls
          dotnet nuget push "*.nupkg" -s "https://api.nuget.org/v3/index.json" -k $env:NUGET_KEY --skip-duplicate        
          dotnet nuget push "*.snupkg" -s "https://api.nuget.org/v3/index.json" -k $env:NUGET_KEY --skip-duplicate        
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
      
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          token: "${{ secrets.RELEASE_TOKEN }}"
